export const inboxTypes = {
    SHOW_POPUP: 'SHOW_POPUP',
    SHOW_ROW_SUBJECT: 'SHOW_ROW_SUBJECT',
    FETCH_INBOX_START: 'FETCH_INBOX_START',
    FETCH_INBOX_SUCCESS: 'FETCH_INBOX_SUCCESS',
    FETCH_INBOX_FAILURE: 'FETCH_INBOX_FAILURE',


}


