export const templatesTypes = {
    FETCH_ALL_TEMPLATES_START: "FETCH_ALL_TEMPLATES_START",
    FETCH_ALL_TEMPLATES_SUCC: "FETCH_ALL_TEMPLATES_SUCC",
    FETCH_ALL_TEMPLATES_FAIL: "FETCH_ALL_TEMPLATES_FAIL"
}