export const interviewsTypes = {
    FETCH_ALL_INTERVIEWS_START: "FETCH_ALL_INTERVIEWS_START",
    FETCH_ALL_INTERVIEWS_SUCC: "FETCH_ALL_INTERVIEWS_SUCC",
    FETCH_ALL_INTERVIEWS_FAIL: "FETCH_ALL_INTERVIEWS_FAIL"
}