export const usersTypes = {
    USER_SIGN_UP_START: "USER_SIGN_UP_START",
    USER_SIGN_UP_SUCC: "USER_SIGN_UP_SUCC",
    USER_SIGN_UP_FAIL: "USER_SIGN_UP_FAIL",
    USER_LOG_OUT: "USER_LOG_OUT",
    COMPLETE_USER_PROFILE : 'COMPLETE_USER_PROFILE'
}